package org.fontainefuturistics.mcalchemy.item;

import org.fontainefuturistics.mcalchemy.MCAlchemy;

import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

public class AllItems {
    
    // The register to add items
    // We add items to this register, then they are registered at a later time under our Mod id
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MCAlchemy.MOD_ID);

    // Make our first item
    /* Steps:
     * 1) Declare and register the item here
     * 2) Add it to a creative mode tab in MCAlchemy.java
     * 3) Set the localization in resources/assets/lang/en_us.json:item.mcalchemy.example_item, the item name URN is generated by ITEMS.register
     * 4) Create a new item model in resources/assets/models/item that references a texture relative to resources/assets/textures
     * 5) Put the texture referenced above in resources/assets/textures/item, textures must be pngs
     */
    public static final DeferredItem<Item> EXAMPLE_ITEM = ITEMS.register("example_item",
            () -> new Item(new Item.Properties()));

    // Make a new item
    public static final DeferredItem<Item> RAW_EXAMPLE_ITEM = ITEMS.register("raw_example_item",
            () -> new Item(new Item.Properties()));

    // Register the items using the event bus, this is called from Main
    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    } // End register

} // End AllItems class